2023-10-02:17:54:08,312 INFO     [Flow.py:147] Imported module: <module 'src.flows.Pirate_Flows' from '/home/suman/Jarvis/src/flows/Pirate_Flows.py'>
2023-10-02:17:54:08,647 INFO     [Flow.py:147] Imported module: <module 'src.flows.Librarian_Flows' from '/home/suman/Jarvis/src/flows/Librarian_Flows.py'>
2023-10-02:17:54:08,651 INFO     [Flow.py:147] Imported module: <module 'src.flows.Remo_Flows' from '/home/suman/Jarvis/src/flows/Remo_Flows.py'>
2023-10-02:17:54:08,653 INFO     [trigger_loader.py:47] !torrent: <class 'src.flows.Pirate_Flows.Torrent'> loaded
2023-10-02:17:54:08,654 INFO     [trigger_loader.py:47] !locate: <class 'src.flows.Librarian_Flows.FileLocator'> loaded
2023-10-02:17:54:08,655 INFO     [trigger_loader.py:47] !upload: <class 'src.flows.Librarian_Flows.FileUploader'> loaded
2023-10-02:17:54:08,655 INFO     [trigger_loader.py:47] !rse: <class 'src.flows.Remo_Flows.RemoteScriptExecution'> loaded
2023-10-02:17:54:08,656 INFO     [trigger_loader.py:47] !local_time: <function UTIL.get_local_time at 0xffff836dde10> loaded
2023-10-02:17:54:08,657 INFO     [trigger_loader.py:47] !cwd: <function UTIL.get_current_working_directory at 0xffff83761090> loaded
2023-10-02:17:54:08,658 INFO     [trigger_loader.py:47] !ip: <function UTIL.get_local_ip_address at 0xffff83761120> loaded
2023-10-02:17:54:08,659 INFO     [trigger_loader.py:47] !ssid: <function UTIL.get_connected_ssid at 0xffff837611b0> loaded
2023-10-02:17:54:08,659 INFO     [trigger_loader.py:47] !temperature: <function UTIL.get_cpu_temperature at 0xffff83761240> loaded
2023-10-02:17:54:08,660 INFO     [trigger_loader.py:47] !wireless_siblings: <function UTIL.discover_wireless_siblings at 0xffff837612d0> loaded
2023-10-02:17:54:08,661 INFO     [trigger_loader.py:47] !reboot: <function UTIL.reboot at 0xffff83761360> loaded
2023-10-02:17:54:08,661 INFO     [trigger_loader.py:47] !shutdown: <function UTIL.shutdown at 0xffff837613f0> loaded
2023-10-02:17:54:13,051 WARNING  [client.py:295] PyNaCl is not installed, voice will NOT be supported
2023-10-02:17:54:13,052 INFO     [Flow.py:147] Imported module: <module 'src.flows.Pirate_Flows' from '/home/suman/Jarvis/src/flows/Pirate_Flows.py'>
2023-10-02:17:54:13,053 INFO     [Flow.py:147] Imported module: <module 'src.flows.Librarian_Flows' from '/home/suman/Jarvis/src/flows/Librarian_Flows.py'>
2023-10-02:17:54:13,053 INFO     [Flow.py:147] Imported module: <module 'src.flows.Remo_Flows' from '/home/suman/Jarvis/src/flows/Remo_Flows.py'>
2023-10-02:17:54:13,054 INFO     [trigger_loader.py:47] !torrent: <class 'src.flows.Pirate_Flows.Torrent'> loaded
2023-10-02:17:54:13,055 INFO     [trigger_loader.py:47] !locate: <class 'src.flows.Librarian_Flows.FileLocator'> loaded
2023-10-02:17:54:13,056 INFO     [trigger_loader.py:47] !upload: <class 'src.flows.Librarian_Flows.FileUploader'> loaded
2023-10-02:17:54:13,056 INFO     [trigger_loader.py:47] !rse: <class 'src.flows.Remo_Flows.RemoteScriptExecution'> loaded
2023-10-02:17:54:13,058 INFO     [trigger_loader.py:47] !local_time: <function UTIL.get_local_time at 0xffff836dde10> loaded
2023-10-02:17:54:13,058 INFO     [trigger_loader.py:47] !cwd: <function UTIL.get_current_working_directory at 0xffff83761090> loaded
2023-10-02:17:54:13,059 INFO     [trigger_loader.py:47] !ip: <function UTIL.get_local_ip_address at 0xffff83761120> loaded
2023-10-02:17:54:13,059 INFO     [trigger_loader.py:47] !ssid: <function UTIL.get_connected_ssid at 0xffff837611b0> loaded
2023-10-02:17:54:13,060 INFO     [trigger_loader.py:47] !temperature: <function UTIL.get_cpu_temperature at 0xffff83761240> loaded
2023-10-02:17:54:13,061 INFO     [trigger_loader.py:47] !wireless_siblings: <function UTIL.discover_wireless_siblings at 0xffff837612d0> loaded
2023-10-02:17:54:13,061 INFO     [trigger_loader.py:47] !reboot: <function UTIL.reboot at 0xffff83761360> loaded
2023-10-02:17:54:13,062 INFO     [trigger_loader.py:47] !shutdown: <function UTIL.shutdown at 0xffff837613f0> loaded
2023-10-02:17:54:13,065 INFO     [client.py:603] logging in using static token
2023-10-02:17:54:14,990 INFO     [gateway.py:561] Shard ID None has connected to Gateway (Session ID: 2f38e900bd4ddc007f362ac0c371614e).
2023-10-02:17:54:17,000 INFO     [bot.py:22] We have logged in as Jarvis-on-pi#1668
2023-10-02:17:54:37,271 INFO     [bot.py:31] Message from Informio
2023-10-02:17:54:58,401 INFO     [bot.py:31] Message from Informio
2023-10-02:17:54:59,061 INFO     [bot.py:27] Message from Self
2023-10-02:17:55:59,661 INFO     [__init__.py:49] file_cache is only supported with oauth2client<4.0.0
2023-10-02:17:56:30,215 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:56:40,218 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:56:50,222 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:00,226 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:10,230 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:20,232 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:30,235 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:40,238 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1364, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1077, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 999, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)

2023-10-02:17:57:50,243 WARNING  [gateway.py:186] Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "/home/suman/Jarvis/Jarvis.py", line 18, in <module>
    discord_app.start()
  File "/home/suman/Jarvis/src/integrations/discord/app.py", line 33, in start
    bot.main()
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 40, in main
    bot.run(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/suman/Jarvis/src/integrations/discord/bot.py", line 35, in on_message
    await self.cmd_matrix.handle(message)
  File "/home/suman/Jarvis/src/integrations/discord/command_matrix.py", line 60, in handle
    await state.job().capture_discord(args, message, self.informio)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 197, in capture_discord
    resp = self.exec(args)
  File "/home/suman/Jarvis/src/flows/Librarian_Flows.py", line 179, in exec
    response = lib.tome_transporter(file_path)
  File "/home/suman/Jarvis/src/services/librarian.py", line 213, in tome_transporter
    ).execute()
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/usr/local/lib/python3.10/dist-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1393, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)

2023-10-02:17:57:51,452 INFO     [gateway.py:550] Shard ID None session has been invalidated.
2023-10-02:17:57:57,719 INFO     [gateway.py:561] Shard ID None has connected to Gateway (Session ID: 6793dcd54750e327d95d142849859cb0).
2023-10-02:17:57:59,728 INFO     [bot.py:22] We have logged in as Jarvis-on-pi#1668
2023-10-02:18:27:31,134 INFO     [gateway.py:566] Shard ID None has successfully RESUMED session 6793dcd54750e327d95d142849859cb0.
